from __future__ import annotations


def build_tutorial(language: str) -> str:
    if language == "my":
        return (
            "📘 Bot အသုံးပြုနည်း လမ်းညွှန်\n"
            "ဒီ Bot က Source channel/group ထဲက post တွေကို Target channel/group ဆီ အလိုအလျောက် repost လုပ်ပေးတဲ့ Bot ဖြစ်ပါတယ်။\n\n"

            "━━━━━━━━━━━━━━━━━━━━\n"
            "✅ စသုံးရန် လိုအပ်တာများ\n"
            "1. OTP / Access key ထည့်ပြီး activate လုပ်ထားရမယ်။\n"
            "2. Source channel/group link ရှိရမယ်။\n"
            "3. Target channel/group link ရှိရမယ်။\n"
            "4. Target မှာ repost account ကို admin ပေးထားရမယ်။\n\n"

            "━━━━━━━━━━━━━━━━━━━━\n"
            "➕ Pair ထည့်မယ် ဆိုတာဘာလဲ?\n"
            "Pair ဆိုတာ Source တစ်ခုကနေ Target တစ်ခုဆီ repost လုပ်ဖို့ ချိတ်ထားတဲ့ setup တစ်ခုပါ။\n\n"
            "ဥပမာ:\n"
            "Source: https://t.me/source_channel\n"
            "Target: https://t.me/target_channel\n\n"
            "ဒီလိုချိတ်လိုက်ရင် Source ထဲက post တွေကို Target ဆီ bot က ပြန်တင်ပေးပါမယ်။\n\n"

            "━━━━━━━━━━━━━━━━━━━━\n"
            "🛠 Pair ထည့်နည်း\n"
            "1. Menu ထဲက “Pair ထည့်မယ်” ကိုနှိပ်ပါ။\n"
            "2. Pair number ပို့ပါ။ ဥပမာ 1, 2, 3\n"
            "3. Source link ပို့ပါ။\n"
            "4. Scan amount ပို့ပါ။ ဥပမာ 50, 100, 300 သို့မဟုတ် all\n"
            "5. Target link ပို့ပါ။\n"
            "6. Ads ထည့်ချင်ရင် ads link/text ပို့ပါ။ မထည့်ချင်ရင် skip ပို့ပါ။\n"
            "7. Post Rule ON/OFF ရွေးပါ။\n"
            "8. Forward Rule ON/OFF ရွေးပါ။\n"
            "9. Remove URL Rule ON/OFF ရွေးပါ။\n"
            "10. Summary ကိုစစ်ပြီး အတည်ပြုပါ။\n\n"

            "━━━━━━━━━━━━━━━━━━━━\n"
            "⚙️ Rule များ အဓိပ္ပာယ်\n\n"
            "🎬 Post Rule\n"
            "ON = video post သို့မဟုတ် video ပါတဲ့ album ကိုအဓိက repost လုပ်မယ်။ Video မတိုင်ခင် post ကို preview အဖြစ်တင်နိုင်တယ်။\n"
            "OFF = post အားလုံးကို repost candidate အဖြစ်သုံးမယ်။\n\n"
            "🔁 Forward Rule\n"
            "ON = forwarded post တွေကို မတင်ဘူး။\n"
            "OFF = forwarded post တွေကိုလည်း တင်ခွင့်ပြုမယ်။\n\n"
            "🔗 Remove URL Rule\n"
            "ON = repost/post mode မှာ text/caption ထဲက visible URL နဲ့ @username တွေကိုဖျက်မယ်။\n"
            "OFF = original text/caption ကို မပြင်ဘဲထားမယ်။\n\n"
            "🔎 Keyword\n"
            "Off = keyword filter မသုံးဘူး။\n"
            "Ban Keyword = အဲဒီစကားလုံးပါတဲ့ post ကို skip လုပ်မယ်။\n"
            "Post Keyword = အဲဒီစကားလုံးပါတဲ့ post ကိုပဲတင်မယ်။\n\n"
            "📢 Ads\n"
            "Ads ဆိုတာ target ဆီတင်မယ့် text/caption အဆုံးမှာ ထည့်မယ့် link/text ဖြစ်ပါတယ်။\n"
            "Ads မထည့်ချင်ရင် skip ပို့နိုင်ပါတယ်။\n\n"

            "━━━━━━━━━━━━━━━━━━━━\n"
            "📋 Menu များ အသုံးပြုနည်း\n"
            "➕ Pair ထည့်မယ် = source -> target setup အသစ်ထည့်မယ်။\n"
            "🗑 Pair ဖျက်မယ် = မလိုချင်တဲ့ pair ကိုဖျက်မယ်။\n"
            "✏️ Source ပြင်မယ် = pair ရဲ့ source ကိုပြောင်းမယ်။\n"
            "🎯 Target ပြင်မယ် = pair ရဲ့ target ကိုပြောင်းမယ်။\n"
            "🔎 Keyword = keyword filter စီမံမယ်။\n"
            "📢 ကြော်ငြာ = ads ထည့်/ဖျက်/ကြည့်မယ်။\n"
            "📊 အခြေအနေ = license, pair count, rules, warning တွေကြည့်မယ်။\n"
            "✅ စစ်မယ် = pair ကိုချက်ချင်းပြန် scan လုပ်မယ်။\n"
            "🔁 Forward Rule = forwarded post တင်/မတင် ပြောင်းမယ်။\n"
            "🎬 Post Rule = video-only style repost rule ပြောင်းမယ်။\n"
            "🔗 Remove URL Rule = URL/@username ဖျက်/မဖျက် ပြောင်းမယ်။\n\n"

            "━━━━━━━━━━━━━━━━━━━━\n"
            "⚠️ မတင်ရင် စစ်ရမယ့်အချက်များ\n"
            "1. Source link မှန်လား စစ်ပါ။\n"
            "2. Private source ဖြစ်ရင် invite link valid ဖြစ်လား စစ်ပါ။\n"
            "3. Target မှာ repost account ကို admin ပေးထားလား စစ်ပါ။\n"
            "4. Post Rule / Forward Rule / Keyword Rule တွေကြောင့် block ဖြစ်နေလား စစ်ပါ။\n"
            "5. အခြေအနေ menu ထဲက Runtime warning ကိုကြည့်ပါ။\n\n"

            "━━━━━━━━━━━━━━━━━━━━\n"
            "🧭 အလွယ်မှတ်ရန်\n"
            "Source = ဖတ်မယ့် channel\n"
            "Target = ပြန်တင်မယ့် channel\n"
            "Pair = Source နဲ့ Target ချိတ်ထားတဲ့ setup\n"
            "Scan = အဟောင်း post ဘယ်လောက်ပြန်စစ်မလဲ\n"
            "Check = ချက်ချင်းပြန် scan လုပ်တာ\n\n"

            "အကူအညီလိုပါက admin ကိုဆက်သွယ်ပါ: @mnsm6003"
        )

    return (
        "📘 Bot User Guide\n"
        "This bot automatically reposts posts from a source channel/group to a target channel/group.\n\n"

        "━━━━━━━━━━━━━━━━━━━━\n"
        "✅ Requirements\n"
        "1. Your OTP/access key must be activated.\n"
        "2. You need a source channel/group link.\n"
        "3. You need a target channel/group link.\n"
        "4. The repost account must be admin in the target.\n\n"

        "━━━━━━━━━━━━━━━━━━━━\n"
        "➕ What is a Pair?\n"
        "A pair is one source -> target repost setup.\n\n"
        "Example:\n"
        "Source: https://t.me/source_channel\n"
        "Target: https://t.me/target_channel\n\n"
        "After creating a pair, the bot watches the source and reposts matching posts to the target.\n\n"

        "━━━━━━━━━━━━━━━━━━━━\n"
        "🛠 How to Add a Pair\n"
        "1. Tap Add Pair.\n"
        "2. Send a pair number, for example 1, 2, 3.\n"
        "3. Send the source link.\n"
        "4. Send scan amount, for example 50, 100, 300, or all.\n"
        "5. Send the target link.\n"
        "6. Send ads text/link, or send skip.\n"
        "7. Choose Post Rule ON/OFF.\n"
        "8. Choose Forward Rule ON/OFF.\n"
        "9. Choose Remove URL Rule ON/OFF.\n"
        "10. Check the summary and confirm.\n\n"

        "━━━━━━━━━━━━━━━━━━━━\n"
        "⚙️ Rules Explained\n\n"
        "🎬 Post Rule\n"
        "ON = video single posts or video albums are main repost candidates. The immediately previous post may be sent as preview.\n"
        "OFF = all posts can be repost candidates.\n\n"
        "🔁 Forward Rule\n"
        "ON = forwarded posts are skipped.\n"
        "OFF = forwarded posts are allowed.\n\n"
        "🔗 Remove URL Rule\n"
        "ON = visible URLs and @usernames in text/caption are removed before repost.\n"
        "OFF = original text/caption is kept.\n\n"
        "🔎 Keyword\n"
        "Off = no keyword filter.\n"
        "Ban Keyword = skip posts containing the keyword.\n"
        "Post Keyword = only repost posts containing the keyword.\n\n"
        "📢 Ads\n"
        "Ads are text/links added at the end of outgoing text/captions.\n"
        "Send skip if you do not want ads.\n\n"

        "━━━━━━━━━━━━━━━━━━━━\n"
        "📋 Menu Guide\n"
        "Add Pair = create a new source -> target setup.\n"
        "Delete Pair = delete an existing pair.\n"
        "Edit Source = change a pair source.\n"
        "Edit Target = change a pair target.\n"
        "Keyword = manage keyword filters.\n"
        "Ads = add/delete/list ads.\n"
        "Status = view license, pairs, rules, and warnings.\n"
        "Check = scan a pair immediately.\n"
        "Forward Rule = control forwarded posts.\n"
        "Post Rule = control video/main repost behavior.\n"
        "Remove URL Rule = remove or keep visible URLs/@usernames.\n\n"

        "━━━━━━━━━━━━━━━━━━━━\n"
        "⚠️ If Nothing Is Posting\n"
        "1. Check whether the source link is correct.\n"
        "2. For private sources, check whether the invite link is valid.\n"
        "3. Make sure the repost account is admin in the target.\n"
        "4. Check whether Post Rule, Forward Rule, or Keyword Rule is blocking posts.\n"
        "5. Check Runtime warning in Status.\n\n"

        "━━━━━━━━━━━━━━━━━━━━\n"
        "🧭 Quick Meaning\n"
        "Source = channel/group to read from\n"
        "Target = channel/group to repost to\n"
        "Pair = one source -> target setup\n"
        "Scan = how many old posts to check\n"
        "Check = scan immediately\n\n"

        "For support, contact admin: @mnsm6003"
    )
