from __future__ import annotations


def build_tutorial(language: str) -> str:
    if language == "my":
        return (
            "Quick setup\n"
            "1. OTP key ထည့်ပါ။\n"
            "2. Add Pair ကိုနှိပ်ပါ။\n"
            "3. Pair number, source, scan amount, target, ads, post rule, forward rule ကို တစ်ဆင့်ချင်းထည့်ပါ။\n"
            "4. Summary ကို Confirm လုပ်ပြီး runtime က source ကိုစောင့်ကြည့်ပါမယ်။\n\n"
            "Full setup guide\n"
            "- ဒီ bot က source channel က post ကို target channel ကို repost လုပ်ပေးပါတယ်။\n"
            "- Source ဆိုတာ post ကိုဖတ်မယ့်နေရာပါ။\n"
            "- Target ဆိုတာ repost ပို့မယ့်နေရာပါ။\n"
            "- စနစ်တစ်ခုလုံးအတွက် shared watcher account တစ်ခုတည်းသုံးပါတယ်။ User session string မလိုပါ။\n"
            "- Public source ကို resolve/watch ပဲလုပ်ပြီး join မလုပ်ပါ။\n"
            "- Private source ကို invite link နဲ့ပဲသုံးရပြီး shared session account က join လုပ်နိုင်ပါတယ်။\n"
            "- Source တစ်ခုကို active pair ဘယ်သူမှမသုံးတော့ရင် shared session က leave လုပ်နိုင်ပါတယ်။\n"
            "- Pair number ဆိုတာ သင့် source -> target setup slot number ဖြစ်ပါတယ်။\n"
            "- Scan amount default က 100 ဖြစ်ပြီး all လည်းရပါတယ်။\n"
            "- Ads ဆိုတာ outgoing caption/text အဆုံးမှာထည့်မယ့် link တွေပါ။\n"
            "- Keyword off = filter မရှိ, ban = keyword ပါရင် skip, post = keyword ပါမှတင်။\n"
            "- Forward Rule ON = forwarded post မတင်။ OFF = forwarded post ကိုခွင့်ပြု။\n"
            "- Post Rule ON = video post/video ပါတဲ့ album ကို main candidate လုပ်ပြီး အရင် post ကို preview အဖြစ်တင်နိုင်။ OFF = post အားလုံး candidate ဖြစ်။\n"
            "- Check က last_processed_id ကနေပြန်စစ်ပါတယ်။\n"
            "- Status က license, pair count, pair summary, rules, warnings ကိုပြပါတယ်။\n"
            "- Back က အရင်အဆင့်ကိုပြန်သွားတာ၊ Cancel က flow တစ်ခုလုံးထွက်ပြီး main menu ပြန်သွားတာပါ။\n\n"
            "Common problems / FAQ\n"
            "- ဘာမှမတင်ဘူးဆိုရင် source မှန်လား, target မှာ shared session ပို့ခွင့်ရှိလား, rules တွေ block လုပ်နေလား စစ်ပါ။\n"
            "- Source resolve မရရင် public link/username မှန်လား, private invite link valid ဖြစ်လား စစ်ပါ။\n"
            "- Target ပို့မရရင် shared watcher account ကို target မှာ member/admin လိုအပ်နိုင်ပါတယ်။\n"
            "- Access expire ဖြစ်ရင် /start နှိပ်ပြီး OTP အသစ်ထည့်ပါ။"
        )
    return (
        "Quick setup\n"
        "1. Enter your OTP key.\n"
        "2. Tap Add Pair.\n"
        "3. Send pair number, source, scan amount, target, ads, post rule, and forward rule step by step.\n"
        "4. Confirm the summary and let the runtime watch your sources.\n\n"
        "Full setup guide\n"
        "- This bot reposts posts from a source channel to a target channel.\n"
        "- A source is where posts are read from.\n"
        "- A target is where reposts are sent to.\n"
        "- The whole service uses one shared watcher account. End users do not provide session strings.\n"
        "- Public sources are resolved and watched only. They are never joined.\n"
        "- Private sources need an invite link. The shared session account may join them when needed.\n"
        "- If an old source is no longer used by any active pair, the shared session account may leave it.\n"
        "- Pair number means your own slot number for one source -> target setup.\n"
        "- Scan amount defaults to 100 and also supports all.\n"
        "- Ads are links appended to outgoing text/captions.\n"
        "- Keyword off = no filter, ban = skip on match, post = repost only on match.\n"
        "- Forward Rule ON = skip forwarded content. OFF = allow forwarded content.\n"
        "- Post Rule ON = only video single posts or albums become main candidates, and the immediately previous post may be reposted as preview. OFF = all posts are candidates.\n"
        "- Check starts from stored last_processed_id.\n"
        "- Status shows your license, pairs, rules, and runtime warnings.\n"
        "- Back returns to the previous step. Cancel exits the full flow and returns to the main menu.\n\n"
        "Common problems / FAQ\n"
        "- If nothing is posting, check whether the source is valid, whether the target is writable by the shared session, and whether the rules are blocking content.\n"
        "- If a source cannot be resolved, verify the public username/link or the private invite link.\n"
        "- If target posting fails, the shared watcher account may need member/admin permissions there.\n"
        "- If access expires, use /start and enter a new OTP key."
    )
